In [1]:
import requests 
import json
import os
from dotenv import load_dotenv
import pandas as pd
from pandas import json_normalize

In [2]:
!pip3 install python-dotenv

Requirement already satisfied: python-dotenv in /home/beatrizsp/anaconda3/envs/ironhack/lib/python3.8/site-packages (0.19.1)

### Importo mi dataframe con información sobre alimentos y sus calorías por porción

In [3]:
df= pd.read_csv("../data/Food and Calories.csv")

### Importo la API elegida con datos nutricionales sobre alimentos, en este caso concretamente para frutas, así podré enriquecer la información de mi dataframe en el que solo obtenía las calorías por porción de alimento

In [4]:
url = "https://www.fruityvice.com/api/fruit/all"

In [5]:
response = requests.get(url)

In [6]:
response

In [7]:
res_js= response.json()

In [8]:
res_js

[{'genus': 'Malus',
  'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 11.4,
   'protein': 0.3,
   'fat': 0.4,
   'calories': 52,
   'sugar': 10.3}},
 {'genus': 'Prunus',
  'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 3.9,
   'protein': 0.5,
   'fat': 0.1,
   'calories': 15,
   'sugar': 3.2}},
 {'genus': 'Musa',
  'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'nutritions': {'carbohydrates': 22,
   'protein': 1,
   'fat': 0.2,
   'calories': 96,
   'sugar': 17.2}},
 {'genus': 'Fragaria',
  'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 5.5,
   'protein': 0,
   'fat': 0.4,
   'calories': 29,
   'sugar': 5.4}},
 {'genus': 'Prunus',
  'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'None',
  'nutritions': {'carbohydrates': 12,
   'protein': 1,
   'fat': 0.3,
   'calories': 50,
   'sugar': 8}},
 {'genus': 'Durio',
  'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'nutritions': {'carbohydrates': 27.1,
   'protein': 1.5,
   'fat': 5.3,
   'calories': 147,
   'sugar': 6.75}},
 {'genus': 'Vitis',
  'name': 'Grapes',
  'id': 47,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'nutritions': {'carbohydrates': 18.1,
   'protein': 0.72,
   'fat': 0.16,
   'calories': 69,
   'sugar': 15.48}},
 {'genus': 'Psidium',
  'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'nutritions': {'carbohydrates': 14,
   'protein': 2.6,
   'fat': 1,
   'calories': 68,
   'sugar': 9}},
 {'genus': 'Citrus',
  'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 9,
   'protein': 1.1,
   'fat': 0.3,
   'calories': 29,
   'sugar': 2.5}},
 {'genus': 'Citrus',
  'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 8.4,
   'protein': 0.3,
   'fat': 0.1,
   'calories': 25,
   'sugar': 1.7}},
 {'genus': 'Mangifera',
  'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 15,
   'protein': 0.82,
   'fat': 0.38,
   'calories': 60,
   'sugar': 13.7}},
 {'genus': 'Cucumis',
  'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'nutritions': {'carbohydrates': 8,
   'protein': 0,
   'fat': 0,
   'calories': 34,
   'sugar': 8}},
 {'genus': 'Citrus',
  'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 8.3,
   'protein': 1,
   'fat': 0.2,
   'calories': 43,
   'sugar': 8.2}},
 {'genus': 'Carica',
  'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Caricacea',
  'nutritions': {'carbohydrates': 11,
   'protein': 0,
   'fat': 0.4,
   'calories': 43,
   'sugar': 1}},
 {'genus': 'Pyrus',
  'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 15,
   'protein': 0.4,
   'fat': 0.1,
   'calories': 57,
   'sugar': 10}},
 {'genus': 'Diospyros',
  'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 18,
   'protein': 0,
   'fat': 0,
   'calories': 81,
   'sugar': 18}},
 {'genus': 'Ananas',
  'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'nutritions': {'carbohydrates': 13.12,
   'protein': 0.54,
   'fat': 0.12,
   'calories': 50,
   'sugar': 9.85}},
 {'genus': 'Rubus',
  'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 12,
   'protein': 1.2,
   'fat': 0.7,
   'calories': 53,
   'sugar': 4.4}},
 {'genus': 'Fragaria',
  'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 5.5,
   'protein': 0.8,
   'fat': 0.4,
   'calories': 29,
   'sugar': 5.4}},
 {'genus': 'Solanum',
  'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'nutritions': {'carbohydrates': 3.9,
   'protein': 0.9,
   'fat': 0.2,
   'calories': 74,
   'sugar': 2.6}},
 {'genus': 'Citrullus',
  'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'nutritions': {'carbohydrates': 8,
   'protein': 0.6,
   'fat': 0.2,
   'calories': 30,
   'sugar': 6}}]

In [9]:
len(res_js)

21

### Obtengo una lista de 21 diccionarios

In [10]:
res_js[0]

{'genus': 'Malus',
 'name': 'Apple',
 'id': 6,
 'family': 'Rosaceae',
 'order': 'Rosales',
 'nutritions': {'carbohydrates': 11.4,
  'protein': 0.3,
  'fat': 0.4,
  'calories': 52,
  'sugar': 10.3}}

## A continuación voy a limpiar mi df eliminando nulos y duplicados, así como comprobando que los nombres de las columnas no contienen espacios o elementos especiales para poder trabajar adecuadamente con ellos

In [11]:
df.head()

        Food              Serving Calories
0  Artichoke  1 artichoke (128 g)   60 cal
1    Arugula         1 leaf (2 g)    1 cal
2  Asparagus       1 spear (12 g)    2 cal
3  Aubergine  1 aubergine (458 g)  115 cal
4   Beetroot        1 beet (82 g)   35 cal

In [12]:
df.shape

(562, 3)

In [13]:
df.dropna(how="all", inplace=True)

In [14]:
df.shape #no hay ninguna fila entera de NaN

(562, 3)

In [15]:
duplicates= df.drop_duplicates() #elimino los duplicados

In [16]:
duplicates.shape

(549, 3)

In [30]:
para_food = {"Food	": "Food"}

In [32]:
duplicates.rename(columns=para_food,inplace=True)

In [33]:
duplicates

                         Food              Serving Calories
0                   Artichoke  1 artichoke (128 g)   60 cal
1                     Arugula         1 leaf (2 g)    1 cal
2                   Asparagus       1 spear (12 g)    2 cal
3                   Aubergine  1 aubergine (458 g)  115 cal
4                    Beetroot        1 beet (82 g)   35 cal
..                        ...                  ...      ...
557  Wendy’s Jr. Cheeseburger     1 burger (129 g)  290 cal
558  Wendy’s Son of Baconator     1 burger (218 g)  700 cal
559                   Whopper     1 burger (291 g)  672 cal
560                    Zinger   1 sandwich (202 g)  517 cal
561             Zinger Burger   1 sandwich (202 g)  517 cal

[549 rows x 3 columns]

### Voy a crearme una lista con todos los alimentos que forman parte de la columna Food, es decir, con todos los valores únicos de la columna.

In [17]:
food = duplicates["Food"].unique()

In [18]:
lista_food_df= list(food)

In [19]:
type(lista_food_df)

list

In [20]:
lista_food_df

['Artichoke',
 'Arugula',
 'Asparagus',
 'Aubergine',
 'Beetroot',
 'Bell Pepper',
 'Black Olives',
 'Broccoli',
 'Brussels Sprouts',
 'Cabbage',
 'Capsicum',
 'Carrot',
 'Cauliflower',
 'Celery',
 'Chard',
 'Cherry Tomato',
 'Chicory',
 'Chinese Cabbage',
 'Chives',
 'Collard Greens',
 'Corn',
 'Courgette',
 'Creamed Spinach',
 'Cucumber',
 'Eggplant',
 'Endive',
 'Fennel',
 'Garlic',
 'Gherkin',
 'Gourd',
 'Green Beans',
 'Green Olives',
 'Green Onion',
 'Horseradish',
 'Kale',
 'Kohlrabi',
 'Kumara',
 'Leek',
 'Lettuce',
 'Mushrooms',
 'Mustard Greens',
 'Nori',
 'Okra',
 'Olives',
 'Onion',
 'Parsnips',
 'Peas',
 'Pepper',
 'Potato',
 'Pumpkin',
 'Radishes',
 'Red Cabbage',
 'Rutabaga',
 'Shallots',
 'Spinach',
 'Squash',
 'Sweet Potato',
 'Tomato',
 'Turnip Greens',
 'Turnips',
 'Wasabi',
 'Winter Squash',
 'Zucchini',
 'Acai',
 'Apple',
 'Applesauce',
 'Apricot',
 'Avocado',
 'Banana',
 'Blackberries',
 'Blood Oranges',
 'Blueberries',
 'Cantaloupe',
 'Cherries',
 'Clementine',
 'Cranberries',
 'Currants',
 'Custard Apple',
 'Dates',
 'Figs',
 'Fruit salad',
 'Grapes',
 'Greengage',
 'Guava',
 'Jackfruit',
 'Jujube',
 'Kiwi',
 'Lemon',
 'Lime',
 'Lychees',
 'Mandarin Oranges',
 'Mango',
 'Minneola',
 'Mulberries',
 'Nectarine',
 'Orange',
 'Papaya',
 'Passion Fruit',
 'Peach',
 'Pear',
 'Persimmon',
 'Physalis',
 'Pineapple',
 'Plantains',
 'Plum',
 'Pomegranate',
 'Quince',
 'Raisins',
 'Rambutan',
 'Raspberries',
 'Rhubarb',
 'Starfruit',
 'Strawberries',
 'Tamarind',
 'Tangerine',
 'Watermelon',
 'Baby Back Ribs',
 'Bacon and Eggs',
 'Baked Beans',
 'BBQ Ribs',
 'Beef Stew',
 'Biryani',
 'Black Pudding',
 'Black Rice',
 'BLT',
 'Brown Rice',
 'Burrito',
 'Butter Chicken',
 'California Roll',
 'Chicken Caesar Salad',
 'Chicken Fried Steak',
 'Chicken Marsala',
 'Chicken Parmesan',
 'Chicken Pot Pie',
 'Chicken Tikka Masala',
 'Chili con Carne',
 'Chimichanga',
 'Cobb Salad',
 'Corn Dog',
 'Corned Beef Hash',
 'Cottage Pie',
 'Dal',
 'Deviled Eggs',
 'Dim Sum',
 'Dosa',
 'Enchiladas',
 'Fajita',
 'Fish and Chips',
 'Fried Rice',
 'Fried Shrimp',
 'Grilled Cheese Sandwich',
 'Ham and Cheese Sandwich',
 'Hummus',
 'Jambalaya',
 'Kebab',
 'Lasagne',
 'Mac and Cheese',
 'Macaroni and Cheese',
 'Mashed Potatoes',
 'Meat Pie',
 'Meatloaf',
 'Naan',
 'Orange Chicken',
 'Pad Thai',
 'Paella',
 'Paratha',
 'Pea Soup',
 'Peanut Butter Sandwich',
 'Peking Duck',
 'Philly Cheese Steak',
 'Pizza',
 'Pork Chop',
 'Potato Salad',
 'Pulled Pork Sandwich',
 'Ramen',
 'Ravioli',
 'Reuben Sandwich',
 'Roast Beef',
 'Roast Dinner',
 'Samosa',
 'Sausage Roll',
 'Sausage Rolls',
 'Shepherds Pie',
 'Shrimp Cocktail',
 'Sloppy Joe',
 'Sloppy Joes',
 'Spaghetti Bolognese',
 'Spring Roll',
 'Spring Rolls',
 'Taco',
 'Tandoori Chicken',
 'Yorkshire Pudding',
 'Amaranth',
 'Barley',
 'Barley Groats',
 'Buckwheat',
 'Buckwheat Groats',
 'Corn Waffles',
 'Cornmeal',
 'Cornstarch',
 'Couscous',
 'Cracker',
 'Durum Wheat Semolina',
 'Flaxseed',
 'Freekeh',
 'Gluten',
 'Grissini',
 'Kamut',
 'Millet',
 'Millet Flour',
 'Millet Gruel',
 'Oat Bran',
 'Pearl Barley',
 'Polenta',
 'Prawn Crackers',
 'Pretzel Sticks',
 'Quinoa',
 'Rusk',
 'Rye Bran',
 'Sago',
 'Savoury Biscuits',
 'Shortbread',
 'Spelt',
 'Spelt Bran',
 'Spelt Semolina',
 'Sunflower Seeds',
 'Tortilla',
 'Tortilla Chips',
 'Wheat Bran',
 'Wheat Germ',
 'Wheat Gluten',
 'Wheat Semolina',
 'Wheat Starch',
 'Whole Grain Wheat',
 'Wholegrain Oat',
 'Almond Oil',
 'Apricot Kernel Oil',
 'Argan Oil',
 'Avocado Oil',
 'Babassu Oil',
 'Canola Oil',
 'Coconut Oil',
 'Corn Oil',
 'Cottonseed Oil',
 'Flaxseed Oil',
 'Grape Seed Oil',
 'Hazelnut Oil',
 'Linseed Oil',
 'Menhaden Oil',
 'Mustard Oil',
 'Oat Oil',
 'Olive Oil',
 'Palm Kernel Oil',
 'Palm Oil',
 'Peanut Oil',
 'Poppy Seed Oil',
 'Pumpkin Seed Oil',
 'Rice Bran Oil',
 'Safflower Oil',
 'Salmon Oil',
 'Sesame Oil',
 'Shea Oil',
 'Soy Oil',
 'Sunflower Oil',
 'Tomato Seed Oil',
 'Vegetable Oil',
 'Walnut Oil',
 'Wheat Germ Oil',
 'Alphabet Soup',
 'Bean Stew',
 'Beef Bouillon',
 'Beef Noodle Soup',
 'Beef Soup',
 'Bouillon',
 'Broccoli Cheese Soup',
 'Broccoli Soup',
 'Cabbage Soup',
 'Carrot Ginger Soup',
 'Carrot Soup',
 'Chicken Bouillon',
 'Chicken Broth',
 'Chicken Gumbo Soup',
 'Chicken Noodle Soup',
 'Chicken Stock',
 'Chicken Vegetable Soup',
 'Chicken with Rice Soup',
 'Cream of Asparagus Soup',
 'Cream of Broccoli Soup',
 'Cream of Celery Soup',
 'Cream of Chicken Soup',
 'Cream of Mushroom Soup',
 'Cream of Onion Soup',
 'Cream of Potato Soup',
 'Creamy Chicken Noodle Soup',
 'French Onion Soup',
 'Golden Mushroom Soup',
 'Goulash',
 'Instant Ramen',
 'Lentil Soup',
 'Lobster Bisque Soup',
 'Meatball Soup',
 'Minestrone',
 'Mushroom Soup',
 'Noodle Soup',
 'Onion Soup',
 'Oxtail Soup',
 'Potato Soup',
 'Pumpkin Soup',
 'Scotch Broth',
 'Succotash',
 'Thai Soup',
 'Tomato Rice Soup',
 'Tomato Soup',
 'Vegetable Beef Soup',
 'Vegetable Broth',
 'Vegetable Soup',
 'Vegetable Stock',
 'Wedding Soup',
 'Baskin-Robbins',
 'Ben and Jerry’s',
 'Butter Pecan Ice Cream',
 'Carvel',
 'Chocolate Chip Ice Cream',
 'Chocolate Ice Cream',
 'Ciao Bella',
 'Coffee Ice Cream',
 'Cold Stone Creamery',
 'Cookie Dough Ice Cream',
 'Crunchie McFlurry',
 'Dairy Milk McFlurry',
 'Dippin Dots',
 'Double Rainbow',
 'Drumsticks',
 'French Vanilla Ice Cream',
 'Friendly’s',
 'Healthy Choice',
 'Hot Fudge Sundae',
 'Ice Cream Sandwich',
 'Ice Cream Sundae',
 'Ice Milk',
 'Magnolia',
 'Magnum',
 'Magnum Almond',
 'Magnum Double Caramel',
 'Magnum Double Chocolate',
 'Magnum Gold',
 'Magnum White',
 'McFlurry',
 'McFlurry Oreo',
 'Mini Milk',
 'Mint Chocolate Chip Ice Cream',
 'Rocky Road Ice Cream',
 'Schwan’s',
 'Smarties McFlurry',
 'Snickers Ice Cream',
 'Soft Serve',
 'Solero',
 'Strawberry Ice Cream',
 'Strawberry Sundae',
 'Sundae',
 'Turkey Hill',
 'Vanilla Cone',
 'Vanilla Ice Cream',
 'Cannelloni',
 'Capellini',
 'Cappelletti',
 'Cellophane Noodles',
 'Cheese Tortellini',
 'Dampfnudel',
 'Dumpling Dough',
 'Egg Noodles',
 'Farfalle',
 'Fettuccine',
 'Fusilli',
 'Glass Noodles',
 'Lasagne Sheets',
 'Linguine',
 'Low Carb Pasta',
 'Macaroni',
 'Manicotti',
 'Mostaccioli',
 'Orecchiette',
 'Orzo',
 'Penne',
 'Penne Rigate',
 'Pierogi',
 'Rigatoni',
 'Rotini',
 'Shells',
 'Shirataki Noodles',
 'Soy Noodles',
 'Spaetzle',
 'Spaghetti',
 'Spinach Tortellini',
 'Spirelli',
 'Tagliatelle',
 'Tortellini',
 'Vermicelli',
 'Whole Grain Noodles',
 'Whole Grain Spaghetti',
 'Ziti',
 'BBQ Chicken Pizza',
 'BBQ Pizza',
 'Beef Pizza',
 'Bianca Pizza',
 'Buffalo Chicken Pizza',
 'Calabrese Pizza',
 'Calzone',
 'Capricciosa Pizza',
 'Cheese Pizza',
 'Chicken Pizza',
 'Deep Dish Pizza',
 'Dominos Philly Cheese Steak Pizza',
 'Four Cheese Pizza',
 'Goat Cheese Pizza',
 'Grilled Pizza',
 'Hawaiian Pizza',
 'Margherita Pizza',
 'Mozzarella Pizza',
 'Mushroom Pizza',
 'Napoli Pizza',
 'New York Style Pizza',
 'Pepperoni Pizza',
 'Pizza Dough',
 'Pizza Hut Stuffed Crust Pizza',
 'Pizza Hut Supreme Pizza',
 'Pizza Rolls',
 'Quattro Formaggi Pizza',
 'Red Pepper Pizza',
 'Salami Pizza',
 'Sausage Pizza',
 'Seafood Pizza',
 'Shrimp Pizza',
 'Sicilian Pizza',
 'Spinach Feta Pizza',
 'Spinach Pizza',
 'Stuffed Crust Pizza',
 'Tarte Flambée',
 'Thin Crust Pizza',
 'Tuna Pizza',
 'Vegetable Pizza',
 'Vegetarian Pizza',
 'Veggie Pizza',
 'White Pizza',
 'Acerola',
 'Asian Pear',
 'Breadfruit',
 'Cantaloupe Melon',
 'Casaba Melon',
 'Cherimoya',
 'Dragon Fruit',
 'Durian',
 'Feijoa',
 'Galia Melon',
 'Grapefruit',
 'Honeydew',
 'Kumquat',
 'Lychee',
 'Mangosteen',
 'Maracuya',
 'Maraschino Cherries',
 'Muskmelon',
 'Noni',
 'Pink Grapefruit',
 'Plantain',
 'Pomelo',
 'Prickly Pear',
 'Sapodilla',
 'Soursop Fruit',
 'Star Fruit',
 'Arby’s Grand Turkey Club',
 'Arby’s Reuben',
 'Arby’s Roast Beef Classic',
 'Arby’s Roast Beef Max',
 'BBQ Rib',
 'Bean Burrito',
 'Big N’ Tasty',
 'Bratwurst',
 'Burger King Angry Whopper',
 'Burger King Double Whopper',
 'Burger King Double Whopper with Cheese',
 'Burger King Original Chicken Sandwich',
 'Burger King Premium Alaskan Fish Sandwich',
 'Burger King Triple Whopper',
 'Burger King Whopper',
 'Burger King Whopper Jr.',
 'Burger King Whopper with Cheese',
 'Cheeseburger',
 'Chicken Breast',
 'Chicken Fajita',
 'Chicken McNuggets',
 'Chicken Nuggets',
 'Chicken Pizziola',
 'Chicken Sandwich',
 'Chicken Teriyaki Sandwich',
 'Chicken Wings',
 'Chop Suey',
 'Curly Fries',
 'Double Cheeseburger',
 'Egg Roll',
 'Falafel',
 'Filet-o-Fish',
 'Fish Sandwich',
 'French Fries',
 'Grilled Chicken Salad',
 'Ham Sandwich',
 'Hamburger',
 'Hot Dog',
 'Italian BMT',
 'Lasagna',
 'McDonald’s Big Mac',
 'McDonald’s Cheeseburger',
 'McDonald’s Chicken Nuggets',
 'McDonald’s Double Cheeseburger',
 'McDonald’s Filet-o-Fish',
 'McDonald’s McChicken',
 'McDonald’s McDouble',
 'McDonald’s McMuffi Egg',
 'McDonald’s McRib',
 'McDonald’s Mighty Wings',
 'McRib',
 'Meatball Sandwich',
 'Nachos with Cheese',
 'Onion Rings',
 'Poutine',
 'Smoked Salmon',
 'Spicy Italian',
 'Subway Club Sandwich',
 'Tortilla Wrap',
 'Tuna',
 'Turkey',
 'Veggie Burger',
 'Veggie Delight',
 'Veggie Patty',
 'Wendy’s Baconator',
 'Wendy’s Jr. Bacon Cheeseburger',
 'Wendy’s Jr. Cheeseburger',
 'Wendy’s Son of Baconator',
 'Whopper',
 'Zinger',
 'Zinger Burger']

### A continuación voy a crearme un dataframe con la información obtenida de la API elegida

In [21]:
para_json = requests.get(url).json()
para_json

[{'genus': 'Malus',
  'name': 'Apple',
  'id': 6,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 11.4,
   'protein': 0.3,
   'fat': 0.4,
   'calories': 52,
   'sugar': 10.3}},
 {'genus': 'Prunus',
  'name': 'Apricot',
  'id': 35,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 3.9,
   'protein': 0.5,
   'fat': 0.1,
   'calories': 15,
   'sugar': 3.2}},
 {'genus': 'Musa',
  'name': 'Banana',
  'id': 1,
  'family': 'Musaceae',
  'order': 'Zingiberales',
  'nutritions': {'carbohydrates': 22,
   'protein': 1,
   'fat': 0.2,
   'calories': 96,
   'sugar': 17.2}},
 {'genus': 'Fragaria',
  'name': 'Blueberry',
  'id': 33,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 5.5,
   'protein': 0,
   'fat': 0.4,
   'calories': 29,
   'sugar': 5.4}},
 {'genus': 'Prunus',
  'name': 'Cherry',
  'id': 9,
  'family': 'Rosaceae',
  'order': 'None',
  'nutritions': {'carbohydrates': 12,
   'protein': 1,
   'fat': 0.3,
   'calories': 50,
   'sugar': 8}},
 {'genus': 'Durio',
  'name': 'Durian',
  'id': 60,
  'family': 'Malvaceae',
  'order': 'Malvales',
  'nutritions': {'carbohydrates': 27.1,
   'protein': 1.5,
   'fat': 5.3,
   'calories': 147,
   'sugar': 6.75}},
 {'genus': 'Vitis',
  'name': 'Grapes',
  'id': 47,
  'family': 'Vitaceae',
  'order': 'Vitales',
  'nutritions': {'carbohydrates': 18.1,
   'protein': 0.72,
   'fat': 0.16,
   'calories': 69,
   'sugar': 15.48}},
 {'genus': 'Psidium',
  'name': 'Guava',
  'id': 37,
  'family': 'Myrtaceae',
  'order': 'Myrtales',
  'nutritions': {'carbohydrates': 14,
   'protein': 2.6,
   'fat': 1,
   'calories': 68,
   'sugar': 9}},
 {'genus': 'Citrus',
  'name': 'Lemon',
  'id': 26,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 9,
   'protein': 1.1,
   'fat': 0.3,
   'calories': 29,
   'sugar': 2.5}},
 {'genus': 'Citrus',
  'name': 'Lime',
  'id': 44,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 8.4,
   'protein': 0.3,
   'fat': 0.1,
   'calories': 25,
   'sugar': 1.7}},
 {'genus': 'Mangifera',
  'name': 'Mango',
  'id': 27,
  'family': 'Anacardiaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 15,
   'protein': 0.82,
   'fat': 0.38,
   'calories': 60,
   'sugar': 13.7}},
 {'genus': 'Cucumis',
  'name': 'Melon',
  'id': 41,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitaceae',
  'nutritions': {'carbohydrates': 8,
   'protein': 0,
   'fat': 0,
   'calories': 34,
   'sugar': 8}},
 {'genus': 'Citrus',
  'name': 'Orange',
  'id': 2,
  'family': 'Rutaceae',
  'order': 'Sapindales',
  'nutritions': {'carbohydrates': 8.3,
   'protein': 1,
   'fat': 0.2,
   'calories': 43,
   'sugar': 8.2}},
 {'genus': 'Carica',
  'name': 'Papaya',
  'id': 42,
  'family': 'Caricaceae',
  'order': 'Caricacea',
  'nutritions': {'carbohydrates': 11,
   'protein': 0,
   'fat': 0.4,
   'calories': 43,
   'sugar': 1}},
 {'genus': 'Pyrus',
  'name': 'Pear',
  'id': 4,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 15,
   'protein': 0.4,
   'fat': 0.1,
   'calories': 57,
   'sugar': 10}},
 {'genus': 'Diospyros',
  'name': 'Persimmon',
  'id': 52,
  'family': 'Ebenaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 18,
   'protein': 0,
   'fat': 0,
   'calories': 81,
   'sugar': 18}},
 {'genus': 'Ananas',
  'name': 'Pineapple',
  'id': 10,
  'family': 'Bromeliaceae',
  'order': 'Poales',
  'nutritions': {'carbohydrates': 13.12,
   'protein': 0.54,
   'fat': 0.12,
   'calories': 50,
   'sugar': 9.85}},
 {'genus': 'Rubus',
  'name': 'Raspberry',
  'id': 23,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 12,
   'protein': 1.2,
   'fat': 0.7,
   'calories': 53,
   'sugar': 4.4}},
 {'genus': 'Fragaria',
  'name': 'Strawberry',
  'id': 3,
  'family': 'Rosaceae',
  'order': 'Rosales',
  'nutritions': {'carbohydrates': 5.5,
   'protein': 0.8,
   'fat': 0.4,
   'calories': 29,
   'sugar': 5.4}},
 {'genus': 'Solanum',
  'name': 'Tomato',
  'id': 5,
  'family': 'Solanaceae',
  'order': 'Solanales',
  'nutritions': {'carbohydrates': 3.9,
   'protein': 0.9,
   'fat': 0.2,
   'calories': 74,
   'sugar': 2.6}},
 {'genus': 'Citrullus',
  'name': 'Watermelon',
  'id': 25,
  'family': 'Cucurbitaceae',
  'order': 'Cucurbitales',
  'nutritions': {'carbohydrates': 8,
   'protein': 0.6,
   'fat': 0.2,
   'calories': 30,
   'sugar': 6}}]

In [23]:
df_api = json_normalize(para_json)

In [24]:
df_api

,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Malus,Apple,6,Rosaceae,Rosales,11.40,0.30,0.40,52,10.30
1,Prunus,Apricot,35,Rosaceae,Rosales,3.90,0.50,0.10,15,3.20
2,Musa,Banana,1,Musaceae,Zingiberales,22.00,1.00,0.20,96,17.20
3,Fragaria,Blueberry,33,Rosaceae,Rosales,5.50,0.00,0.40,29,5.40
4,Prunus,Cherry,9,Rosaceae,None,12.00,1.00,0.30,50,8.00
5,Durio,Durian,60,Malvaceae,Malvales,27.10,1.50,5.30,147,6.75
6,Vitis,Grapes,47,Vitaceae,Vitales,18.10,0.72,0.16,69,15.48
7,Psidium,Guava,37,Myrtaceae,Myrtales,14.00,2.60,1.00,68,9.00
8,Citrus,Lemon,26,Rutaceae,Sapindales,9.00,1.10,0.30,29,2.50
9,Citrus,Lime,44,Rutaceae,Sapindales,8.40,0.30,0.10,25,1.70
10,Mangifera,Mango,27,Anacardiaceae,Sapindales,15.00,0.82,0.38,60,13.70
11,Cucumis,Melon,41,Cucurbitaceae,Cucurbitaceae,8.00,0.00,0.00,34,8.00
12,Citrus,Orange,2,Rutaceae,Sapindales,8.30,1.00,0.20,43,8.20
13,Carica,Papaya,42,Caricaceae,Caricacea,11.00,0.00,0.40,43,1.00
14,Pyrus,Pear,4,Rosaceae,Rosales,15.00,0.40,0.10,57,10.00
15,Diospyros,Persimmon,52,Ebenaceae,Rosales,18.00,0.00,0.00,81,18.00
16,Ananas,Pineapple,10,Bromeliaceae,Poales,13.12,0.54,0.12,50,9.85
17,Rubus,Raspberry,23,Rosaceae,Rosales,12.00,1.20,0.70,53,4.40
18,Fragaria,Strawberry,3,Rosaceae,Rosales,5.50,0.80,0.40,29,5.40
19,Solanum,Tomato,5,Solanaceae,Solanales,3.90,0.90,0.20,74,2.60
20,Citrullus,Watermelon,25,Cucurbitaceae,Cucurbitales,8.00,0.60,0.20,30,6.00

### Compruebo que valores de la columna "Food" de mi df inicial y los valores de la columna "name" del df obtenido de la API coinden, por tanto puedo unir ambos dataframes por dichas columnas.

In [25]:
mergeado = df.merge(df_api,left_on="Food", right_on="name", suffixes=["_izq", "_dcha"] )

In [35]:
mergeado.head()

,Food,Serving,Calories,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Tomato,1 tomato (111 g),20 cal,Solanum,Tomato,5,Solanaceae,Solanales,3.9,0.9,0.2,74,2.6
1,Apple,1 apple (182 g),95 cal,Malus,Apple,6,Rosaceae,Rosales,11.4,0.3,0.4,52,10.3
2,Apricot,1 apricot (35 g),17 cal,Prunus,Apricot,35,Rosaceae,Rosales,3.9,0.5,0.1,15,3.2
3,Banana,1 banana (125 g),111 cal,Musa,Banana,1,Musaceae,Zingiberales,22.0,1.0,0.2,96,17.2
4,Banana,1 banana (125 g),111 cal,Musa,Banana,1,Musaceae,Zingiberales,22.0,1.0,0.2,96,17.2

In [36]:
mergeado.drop(columns=["name"]).head()

,Food,Serving,Calories,genus,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Tomato,1 tomato (111 g),20 cal,Solanum,5,Solanaceae,Solanales,3.9,0.9,0.2,74,2.6
1,Apple,1 apple (182 g),95 cal,Malus,6,Rosaceae,Rosales,11.4,0.3,0.4,52,10.3
2,Apricot,1 apricot (35 g),17 cal,Prunus,35,Rosaceae,Rosales,3.9,0.5,0.1,15,3.2
3,Banana,1 banana (125 g),111 cal,Musa,1,Musaceae,Zingiberales,22.0,1.0,0.2,96,17.2
4,Banana,1 banana (125 g),111 cal,Musa,1,Musaceae,Zingiberales,22.0,1.0,0.2,96,17.2

In [28]:
duplicates2= mergeado.drop_duplicates()

In [34]:
duplicates2.head()

,Food,Serving,Calories,genus,name,id,family,order,nutritions.carbohydrates,nutritions.protein,nutritions.fat,nutritions.calories,nutritions.sugar
0,Tomato,1 tomato (111 g),20 cal,Solanum,Tomato,5,Solanaceae,Solanales,3.9,0.90,0.20,74,2.60
1,Apple,1 apple (182 g),95 cal,Malus,Apple,6,Rosaceae,Rosales,11.4,0.30,0.40,52,10.30
2,Apricot,1 apricot (35 g),17 cal,Prunus,Apricot,35,Rosaceae,Rosales,3.9,0.50,0.10,15,3.20
3,Banana,1 banana (125 g),111 cal,Musa,Banana,1,Musaceae,Zingiberales,22.0,1.00,0.20,96,17.20
5,Grapes,1 cup (151 g),104 cal,Vitis,Grapes,47,Vitaceae,Vitales,18.1,0.72,0.16,69,15.48